version: "3.11"

services:
  app:
    build: .
    volumes:
      - .:/stamaaws
    ports:
      - "8000:8000"
    image: application:django
    container_name: stama
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000