# Generated by Django 4.2.3 on 2023-09-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stamapro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="additional_features",
            field=models.TextField(blank=True, null=True),
        ),
    ]
