# Generated by Django 4.2.3 on 2023-09-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stamapro", "0002_client_message_alter_client_additional_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="number_of_rooms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
