# Generated by Django 4.2.3 on 2023-09-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stamapro", "0003_alter_client_number_of_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
