# Generated by Django 4.2.3 on 2023-07-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodations", "0004_alter_hostel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="stama_id",
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
