# Generated by Django 4.2.3 on 2023-07-22 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accommodations", "0005_alter_hostel_stama_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="room_count",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.CharField(max_length=20, unique=True)),
                ("room_number", models.CharField(max_length=999999)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OC", "Occupied"),
                            ("UC", "Unoccupied"),
                            ("UNAV", "Unavailable"),
                        ],
                        default="UC",
                        max_length=20,
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="accommodations.hostel",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
