# Generated by Django 4.2.3 on 2023-07-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodations", "0007_alter_hostel_room_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.CharField(max_length=3),
        ),
    ]
