# Generated by Django 4.2.3 on 2023-08-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodations", "0008_alter_room_room_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="amenities",
            field=models.TextField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name="hostel",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
