# Generated by Django 4.2.3 on 2023-08-26 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accommodations", "0009_alter_hostel_amenities_alter_hostel_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=30)),
                ("speciality", models.CharField(max_length=30)),
                ("contact", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="hostel",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accommodations.workers",
            ),
        ),
    ]
