# Generated by Django 4.2.3 on 2023-08-27 16:49

import accommodations.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodations", "0010_workers_hostel_worker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accommodations.models.unique_file_path,
                validators=[accommodations.models.validate_file_size],
            ),
        ),
    ]
