# Generated by Django 4.2.3 on 2023-08-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodations", "0014_alter_hostel_manager"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Workers",
            new_name="Operative",
        ),
        migrations.RemoveField(
            model_name="hostel",
            name="worker",
        ),
        migrations.AddField(
            model_name="hostel",
            name="operative",
            field=models.ManyToManyField(
                blank=True, null=True, to="accommodations.operative"
            ),
        ),
    ]
