# Generated by Django 4.2.3 on 2023-08-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accommodations",
            "0015_rename_workers_operative_remove_hostel_worker_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="operative",
            field=models.ManyToManyField(blank=True, to="accommodations.operative"),
        ),
    ]
