# Generated by Django 4.2.3 on 2023-08-31 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accommodations", "0016_alter_hostel_operative"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hostel",
            name="operative",
        ),
        migrations.AddField(
            model_name="operative",
            name="hostel",
            field=models.ForeignKey(
                blank=True,
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accommodations.hostel",
            ),
        ),
        migrations.AlterField(
            model_name="operative",
            name="full_name",
            field=models.CharField(max_length=50),
        ),
    ]
