# Generated by Django 4.2.3 on 2023-09-08 16:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accommodations", "0020_genaralmessage_delete_announcement"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GenaralMessage",
            new_name="GeneralMessage",
        ),
    ]
