# Generated by Django 4.2.3 on 2023-07-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_tenant_stama_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="matric_num",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
