# Generated by Django 4.2.3 on 2023-07-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_tenant_middle_initial_alter_tenant_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
    ]
