# Generated by Django 4.2.3 on 2023-07-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_tenant_first_name_alter_tenant_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="user_image",
            field=models.ImageField(blank=True, null=True, upload_to="users/"),
        ),
    ]
