# Generated by Django 4.2.3 on 2023-07-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_tenant_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="level",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
