# Generated by Django 4.2.3 on 2023-07-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_tenant_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="middle_initial",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
