# Generated by Django 4.2.3 on 2023-07-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_tenant_phone_number_alter_tenant_middle_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
