# Generated by Django 4.2.3 on 2023-08-13 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_tenant_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="rent_start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
