# Generated by Django 4.2.3 on 2023-08-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_tenant_rent_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="department",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="faculty",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="last_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="matric_num",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="sex",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
