# Generated by Django 4.2.3 on 2023-08-26 12:52

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_tenant_department_alter_tenant_faculty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="user_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.unique_file_path
            ),
        ),
    ]
