# Generated by Django 4.2.3 on 2023-08-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_alter_tenant_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="nok_email",
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="nok_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="nok_phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
