# Generated by Django 4.2.3 on 2023-08-27 16:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_tenant_nok_email_tenant_nok_name_tenant_nok_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="user_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.unique_file_path,
                validators=[accounts.models.validate_file_size],
            ),
        ),
    ]
