# Generated by Django 4.2.3 on 2023-08-30 20:57

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_alter_tenant_matric_num"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagerProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.tenant",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
