# Generated by Django 4.2.3 on 2023-08-06 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accommodations", "0009_alter_hostel_amenities_alter_hostel_phone"),
        ("maintenance", "0002_maintenance_repair_id_alter_maintenance_subtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance",
            name="hostel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repairs",
                to="accommodations.hostel",
            ),
        ),
    ]
