# Generated by Django 4.2.3 on 2023-08-06 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0003_maintenance_hostel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenance",
            name="hostel",
        ),
    ]
