# Generated by Django 4.2.3 on 2023-08-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "maintenance",
            "0005_remove_maintenance_subtype_maintenancetype_parent_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenancetype",
            name="parent",
        ),
        migrations.CreateModel(
            name="MaintenanceSubType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtypes",
                        to="maintenance.maintenancetype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="maintenance",
            name="subtype",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repairs",
                to="maintenance.maintenancesubtype",
            ),
        ),
    ]
