# Generated by Django 4.2.3 on 2023-08-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "maintenance",
            "0006_remove_maintenancetype_parent_maintenancesubtype_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenance",
            name="subtype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repairs",
                to="maintenance.maintenancesubtype",
            ),
        ),
    ]
