# Generated by Django 4.2.3 on 2023-08-13 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0010_rename_comment_note_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="time_added",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
