# Generated by Django 4.2.3 on 2023-08-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0011_note_time_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="time_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
