# Generated by Django 4.2.3 on 2023-08-17 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0012_alter_note_time_added"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="description",
            new_name="maintenance",
        ),
    ]
