# Generated by Django 4.2.3 on 2023-08-19 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0013_rename_description_note_maintenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance",
            name="time_created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
