# Generated by Django 4.2.3 on 2023-08-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0014_maintenance_time_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenance",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("WP", "Work In Progress"),
                    ("INP", "Inspection"),
                    ("C", "Completed"),
                ],
                default="P",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="time_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
