# Generated by Django 4.2.3 on 2023-08-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0015_alter_maintenance_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance",
            name="contact",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
